# Generated by Django 4.2 on 2023-04-15 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoderApp3', '0002_dt_socio_alter_jugador_numero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socio',
            name='SocioNro',
            field=models.IntegerField(),
        ),
    ]
